sudo: false
language: node_js
node_js:
- 4.2.2
before_script:
- npm install -g gulp
script:
- gulp buildSass
- gulp buildMagicBox
- gulp test
after_success:
- gulp uglify
cache:
  directories:
  - node_modules
skip_cleanup: true
notifications:
  email:
    on_success: never
    on_failure: never
deploy:
  provider: npm
  email: sandbox_JSUI@coveo.com
  api_key:
    secure: dJt0lYkR2BTvmP+XlEOiDvSWT9t5uj7e01oFTjpvv7wBCUO4ecRwCsDAkWenHul4pLnQIunoN1Of+/j43RqR102v5iGrqGUwbIzgmTFPTQaw6n0d2fXSuI9F/ThfhMO73d3pOlEwjsgKXXKxDR56/hIzn+wxUrPNo7MNcbD4uOa3hgOCn/KuuVq5nis1rtJxjRj1sbln7EnT6R02RDfqfNhvRWyxCbA0Zwaa8mR107jgk1A36xa0dU/ry0F+VD2jWN5RKOcWWCz61WarGafaN69P9rcKXeaz4f8qHfn4BMgl4ncxlvhKgm/zVvtyyiVmZ0v2Oa0puLYD9Ej1MGF3XJ+COGl+prHxANBN3L3SaBf6Wh67HdrlOObTCbHLhP0WdSwEqCB5oR/LGRBQbkw1uxGNVwqQlPVEcdXGsoCMcRwtvwnx42D0drivPo+EZgR01MoaC9jcPX/np5fXVqN+QL3jC34nAnX3XhTRwqcPHXg67iMTRNqoBUd5OCjDK92W/vtFS4IlFFuQUaaN5N2SUIYl37uBtIlcmd6jK3uBLkB0T85qRa8JD+0EjkVV8goLE1RaFMEERH3ZCpWzRAI3a0j7FuQjiB64vjOFtAUC2pAO7yEBicOHLrnEEHMXYWQEVQQEbFZ36VcwypCV4+/SVrW18gn5tP852urh10vW3Yw=
  on:
    tags: true
    repo: coveo/magicbox
